name: chat_app_firebase
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  injectable: ^2.4.2
  get_it: ^7.7.0
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  firebase_storage: ^12.0.1
  cloud_firestore: ^5.0.1
  intl: ^0.19.0
  uuid: ^4.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  image_picker: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy-regular.ttf
        - asset: assets/fonts/gilroy-black.ttf
          weight: 700

